services:
  minio:
    image: minio/minio:latest
    container_name: mf-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    environment:
      MINIO_CERTS_DIR: /home/minio/.minio/certs
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
      - /opt/minio/certs:/root/.minio/certs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio-net

  mf-downloader:
    build: ./downloader
    image: mf-downloader:latest
    env_file:
      - .env
    container_name: mf-downloader
    restart: always
    networks:
      - minio-net
    extra_hosts:
      - "minio.warchd.ovh:172.18.0.2"

volumes:
  minio_data:

networks:
  minio-net: